# File to provision a cluster using the command line
# ic cs cluster-create [--file FILE_LOCATION]
name: dev-cluster
zone: fra02
# no-subnet: <no-subnet>
# ic cs machine-types fra02
machine-type: b2c.4x16
# ic cs vlans fra02
private-vlan: 2268624
public-vlan: 2268622
# shared or dedicated
hardware: shared
# Number_workers
workerNum: 3
kube-version: 1.11.2